### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by BryanSechan** [akasakaid/gameetod#10]
Waktu Claim Lebih Cepat Bisa bang ini ?

**Comment by akasakaid** [comment]
> Waktu Claim Lebih Cepat Bisa bang ini ?

Bisa, udah countdown di file config.json. Itu hitungannya detik jadi kalau pengen ngeubah ke 1 menit itu ubah jadi 60

**Comment by BryanSechan** [comment]
Cara set nya gmna ya bang gw pake termux comand nya apa?

**Comment by akasakaid** [comment]
> Cara set nya gmna ya bang gw pake termux comand nya apa?

Pakai nano

```
nano config.json
```

Kalau belum install nano
```
pkg install nano
```

Sorry baru bales.

**Comment by akasakaid** [comment]
> > Cara set nya gmna ya bang gw pake termux comand nya apa?
> 
> Pakai nano
> 
> ```
> nano config.json
> ```
> 
> Kalau belum install nano
> ```
> pkg install nano
> ```
> 
> Sorry baru bales.

Kalau nga tau cara save-nya bisa cari digoogle.

**Comment by akasakaid** [comment]
> ![1720442867428.jpg](https://github.com/akasakaid/gameetod/assets/160688158/c63f3c50-e204-47b5-b965-f423911e15f0)
> 
> Kalo Begini Kenapa ya bang ? Tiba eror saya pakai termuis

Mungkin kelebihan enter, coba diperiksa lagi datanya.

**Comment by BryanSechan** [comment]
Done bang
