### ISSUE TITLE
the bot is not using the tickets

### ISSUE THREAD

**Issue by supmyhava** [akasakaid/gameetod#11]
the bot is not using the tickets =\

**Comment by supmyhava** [comment]
also i think they has changed the way that the query id if shown... they remove it or something

**Comment by akasakaid** [comment]
> also i think they has changed the way that the query id if shown... they remove it or something

I will check later, i have'nt run this script bot lately.

**Comment by supmyhava** [comment]
> > also i think they has changed the way that the query id if shown... they remove it or something
> 
> I will check later, i have'nt run this script bot lately.

thanks mate. really appreciate it
