### ISSUE TITLE
Banned Kah ini Bang ? 

### ISSUE THREAD

**Issue by BryanSechan** [akasakaid/gameetod#12]
![Screenshot_20240715-134846.jpg](https://github.com/user-attachments/assets/06d43e4a-77ac-42d2-b918-a37ef27ac3e7)

**Comment by BryanSechan** [comment]
![Screenshot_20240715-212127.jpg](https://github.com/user-attachments/assets/1fe41736-804a-4a8b-be57-56bb92326b16)

Sudah normal tapi masih suka stop berhenti begini bang kenapa ya?

**Comment by ilcham0202** [comment]
itu ipnya ke block cloudflare bang, harus ganti ip
