### ISSUE TITLE
update is needed ?

### ISSUE THREAD

**Issue by supmyhava** [akasakaid/gameetod#14]
hi mate
the bot is need an update because they remove the mine ? or can we keep using it like so...?
thank you!!

**Comment by Sergey12345678** [comment]
Dear professional, the mining in the gamee is finished, and it was changed on mining game, is it possible to update your script for auto playing in this game, of course if you have time and desire?

**Comment by supmyhava** [comment]
> Dear professional, the mining in the gamee is finished, and it was changed on mining game, is it possible to update your script for auto playing in this game, of course if you have time and desire?

i think we need to wait for akasakaid to reply

**Comment by akasakaid** [comment]
Sorry, i have a task for completing first. Maybe i will update if have free time tomorrow.

**Comment by supmyhava** [comment]
> Sorry, i have a task for completing first. Maybe i will update if have free time tomorrow.

ahh thats ok my friend we will wait for your update.
thanks for what yo doing
