### ISSUE TITLE
salah ga nih

### ISSUE THREAD

**Issue by isrealllairdrop** [akasakaid/gameetod#2]
kok blumtod

**Comment by akasakaid** [comment]
awkokwoaw lupa belom ganti

**Comment by isrealllairdrop** [comment]
![image](https://github.com/akasakaid/gameetod/assets/167641753/5e98176f-c119-44df-8dc3-4b1f58e308aa)

**Comment by akasakaid** [comment]
data antum kureng

**Comment by isrealllairdrop** [comment]
gajadi gajadi, udah bisa, ane ambil langsung dari application session malah bisa hehe

**Comment by akasakaid** [comment]
oke oke
