### ISSUE TITLE
Failed to get json response 

### ISSUE THREAD

**Issue by FarmTon** [akasakaid/gameetod#20]
Hi, anyone else facing this?

**Comment by Mtwserv** [comment]
> Hi, anyone else facing this?

Yeah

**Comment by ShmilyGone** [comment]
Me too, how to fix this?

**Comment by bond2bill** [comment]
that is cloudflare challenge, how to fix author?

**Comment by akasakaid** [comment]
I've done an update just now, maybe you can try it. 
Please also read this message https://t.me/sdsproject/78?single (translate into your language)

**Comment by FarmTon** [comment]
> I've done an update just now, maybe you can try it. Please also read this message https://t.me/sdsproject/78?single (translate into your language)

goat

**Comment by jerrydao** [comment]
It works yesterday, now not working again with Json error

**Comment by FarmTon** [comment]
> It works yesterday, now not working again with Json error. I have tried to deleted old files, download new one, still facing Json error.

It works for me so i cant help, share http log
