### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by doubleTroub1e** [akasakaid/gameetod#3]
hey, faced issue like this:
<img width="584" alt="image" src="https://github.com/akasakaid/gameetod/assets/18425295/5a2c4c5f-52e8-4245-b53f-2150d861016e">

Also, is there any other way. maybe a bit easier to get this query? maybe from web.telegram or so  as there are no experimental features on Mac OS

**Comment by akasakaid** [comment]
First, you can open the http.log file for check the http request result.
And second question, last  i have try to get data from web browser (web.telegram.org) and the bot is not respond, the bot show me black blank page.

**Comment by doubleTroub1e** [comment]
ah, thanks, first log was good, without errors, but second one error is
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Server error","data":{"reason":"Server error"}},"id":null,"time":"2024-06-13T14:23:11+00:00"}

about connecting in another way  - you may check this repo https://github.com/shamhi/MemeFiBot
here is telegram session is creating separately and then using it - working like a charm

**Comment by doubleTroub1e** [comment]
fyi: 
 
![image](https://github.com/akasakaid/gameetod/assets/18425295/91a678f5-b052-4756-9a7f-749914ec7081)

**Comment by doubleTroub1e** [comment]
solved!
fyi: I took query as shown on screenshot above and now it is working for me - thank you!
<img width="449" alt="image" src="https://github.com/akasakaid/gameetod/assets/18425295/b94c9ce2-7700-4d49-a872-5721865abc43">

**Comment by akasakaid** [comment]
> ah, thanks, first log was good, without errors, but second one error is {"jsonrpc":"2.0","error":{"code":-32603,"message":"Server error","data":{"reason":"Server error"}},"id":null,"time":"2024-06-13T14:23:11+00:00"}
> 
> about connecting in another way - you may check this repo https://github.com/shamhi/MemeFiBot here is telegram session is creating separately and then using it - working like a charm

okay i will try to fix later, and running a bot using a session is a bit dangerous because it can get your account banned from telegram. So I took the step of using query_id=xxx data for the process

**Comment by akasakaid** [comment]
> solved! fyi: I took query as shown on screenshot above and now it is working for me - thank you! <img alt="image" width="449" src="https://private-user-images.githubusercontent.com/18425295/339466808-b94c9ce2-7700-4d49-a872-5721865abc43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTU4MDQsIm5iZiI6MTcxODI5NTUwNCwicGF0aCI6Ii8xODQyNTI5NS8zMzk0NjY4MDgtYjk0YzljZTItNzcwMC00ZDQ5LWE4NzItNTcyMTg2NWFiYzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE2MTgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0Zjg2MzkyZmExNDE0NjM1ZmM3NzcwM2MzZTBiNmU4ZWQ5ZGI1YjcyZGU4MjU2MTI0NzcyM2E2YTg3M2U0OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SbGirNrB_PnswsI3JQGIwXzSh88GTODabsUbOccgxhw">

sound good

**Comment by doubleTroub1e** [comment]
btw, here is also pretty cool project which is worth to be automated, and as for now - I was able to find only 1 automation - but it is pretty hard to start on raspberry pi and resource consuming
https://t.me/oxygenminerbot?start=595909481

**Comment by akasakaid** [comment]
> btw, here is also pretty cool project which is worth to be automated, and as for now - I was able to find only 1 automation - but it is pretty hard to start on raspberry pi and resource consuming

Okay i will try later when im free

**Comment by doubleTroub1e** [comment]
also, very cool proejct, simple coin - they do have website and they do an app to  byu/sell crypto via phone, like phone bank, I do belive that is for sure better then previous project I share, and I can't find  any automation at GitHub at all 
https://t.me/Simple_Tap_Bot?start=1716824326795

**Comment by doubleTroub1e** [comment]
> > btw, here is also pretty cool project which is worth to be automated, and as for now - I was able to find only 1 automation - but it is pretty hard to start on raspberry pi and resource consuming
> 
> Okay i will try later when im free

thank you) won't spam any more)

**Comment by akasakaid** [comment]
> thank you) won't spam any more)

no problem sir, github create this function and yeah we must use it. dont worry
