### ISSUE TITLE
Error, keyError query_id

### ISSUE THREAD

**Issue by unh4cked** [akasakaid/gameetod#4]
[2024-06-22 09:50:21] login as Boolean
Traceback (most recent call last):
  File "/home/unhckedc/files/adrop/gameetod/bot.py", line 353, in <module>
    app.main()
  File "/home/unhckedc/files/adrop/gameetod/bot.py", line 325, in main
    data = f"query_id={data_parse['query_id']}&user={quote(data_parse['user'])}&auth_date={data_parse['auth_date']}&hash={data_parse['hash']}"
                       ~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'query_id'

how i can fix it

**Comment by akasakaid** [comment]
> [2024-06-22 09:50:21] login as Boolean
> Traceback (most recent call last):
>   File "/home/unhckedc/files/adrop/gameetod/bot.py", line 353, in <module>
>     app.main()
>   File "/home/unhckedc/files/adrop/gameetod/bot.py", line 325, in main
>     data = f"query_id={data_parse['query_id']}&user={quote(data_parse['user'])}&auth_date={data_parse['auth_date']}&hash={data_parse['hash']}"
>                        ~~~~~~~~~~^^^^^^^^^^^^
> KeyError: 'query_id'
> 
> how i can fix it

'query_id' is not found in your data. Get your data again.

**Comment by DonyShaputra** [comment]
> > [2024-06-22 09:50:21] login as Boolean
> > Traceback (most recent call last):
> > File "/home/unhckedc/files/adrop/gameetod/bot.py", line 353, in 
> > app.main()
> > File "/home/unhckedc/files/adrop/gameetod/bot.py", line 325, in main
> > data = f"query_id={data_parse['query_id']}&user={quote(data_parse['user'])}&auth_date={data_parse['auth_date']}&hash={data_parse['hash']}"
> > ~~~~~~~~~~^^^^^^^^^^^^
> > KeyError: 'query_id'
> > how i can fix it
> 
> 'query_id' is not found in your data. Get your data again.


akun saya yang satu nya user_id bukan query_id , error nya seperti itu

**Comment by akasakaid** [comment]
> > > [2024-06-22 09:50:21] login as Boolean
> > > Traceback (most recent call last):
> > > File "/home/unhckedc/files/adrop/gameetod/bot.py", line 353, in
> > > app.main()
> > > File "/home/unhckedc/files/adrop/gameetod/bot.py", line 325, in main
> > > data = f"query_id={data_parse['query_id']}&user={quote(data_parse['user'])}&auth_date={data_parse['auth_date']}&hash={data_parse['hash']}"
> > > ```
> > > KeyError: 'query_id'
> > > how i can fix it
> > > ```
> > 
> > 
> > 'query_id' is not found in your data. Get your data again.
> 
> akun saya yang satu nya user_id bukan query_id , error nya seperti itu

coba klik tombol yang ada disebelah kiri kolom pesan "open app"

**Comment by DonyShaputra** [comment]
> > > > [2024-06-22 09:50:21] login as Boolean
> > > > Traceback (most recent call last):
> > > > File "/home/unhckedc/files/adrop/gameetod/bot.py", line 353, in
> > > > app.main()
> > > > File "/home/unhckedc/files/adrop/gameetod/bot.py", line 325, in main
> > > > data = f"query_id={data_parse['query_id']}&user={quote(data_parse['user'])}&auth_date={data_parse['auth_date']}&hash={data_parse['hash']}"
> > > > ```
> > > > KeyError: 'query_id'
> > > > how i can fix it
> > > > ```
> > > 
> > > 
> > > 'query_id' is not found in your data. Get your data again.
> > 
> > 
> > akun saya yang satu nya user_id bukan query_id , error nya seperti itu
> 
> coba klik tombol yang ada disebelah kiri kolom pesan "open app"

oiya udah bisa , makasih
