### ISSUE TITLE
multi account issue

### ISSUE THREAD

**Issue by Masalik45** [akasakaid/gameetod#5]
mentok di akun pertama sir

**Comment by erosakti** [comment]
sama

**Comment by bacnd** [comment]
Please change https://api.service.gameeapp.com to https://api.gamee.com  and line 220 change 7 to 11

**Comment by Masalik45** [comment]
> https://api.gamee.com

work smoothly with this method, tyvm

**Comment by akasakaid** [comment]
has you problem have been fixed?
