### ISSUE TITLE
The problem sir

### ISSUE THREAD

**Issue by Gevalio7** [akasakaid/gameetod#7]
![image](https://github.com/akasakaid/gameetod/assets/146747522/a803f52b-4b44-4e39-b81f-29d12dd8ee77)
how to get an identifier in this case

**Comment by akasakaid** [comment]
1. goto console menu 
2. copy and paste the following command
```javascript
copy(Telegram.WebApp.initData)
```
after that try to paste on notepad or something like that.

if query_id not showing, try goto application menu -> click session storage -> click that have gamee url -> click initparams -> and maybe the query_id is showing.

try method in above

**Comment by Gevalio7** [comment]
![image](https://github.com/akasakaid/gameetod/assets/146747522/365926dc-d88c-497a-832e-6857cf8afa38)
I found it, thanks

**Comment by akasakaid** [comment]
> ![image](https://github.com/akasakaid/gameetod/assets/146747522/365926dc-d88c-497a-832e-6857cf8afa38)
> I found it, thanks

Sound good
